- .circleci/config.yml
Reverts powerapi-ng/powerapi#21
> Revert "build: automatic release creation on github"

- powerapi/formula/dummy/dummy_formula_actor.py
- powerapi/formula/formula_actor.py
Add type hint for pusher_actors
> fix: Add fix for pusher_actors with type hint

- powerapi/report/formula_report.py
- powerapi/report/power_report.py
This adds the Formula report used to store information about a running formula.
This is useful to gather information about a running formula in order to debug or compute statistics.
> Add Formula report

- .dockerignore
- .gitignore
- Dockerfile
PR overview:
- Clean gitignore file by removing useless constraints ;
- Use pip install in normal mode instead of development mode ;
- Add dockerignore to filter the files included into the docker context when building the Docker image.
> Docker image building optimizations

- docs/source/conf.py
- powerapi/report_model/hwpc_model.py
- powerapi/report_model/power_model.py
- powerapi/report_model/report_model.py
- setup.cfg
> Autodoc with typehint 

- powerapi/cli/tools.py
> Cli support for influxdb

- powerapi/cli/tools.py
- powerapi/report/__init__.py
- powerapi/report/control_report.py
- powerapi/report_model/control_model.py
This PR add a new "ControlReport"
> Add Control Report

- docs/source/quickstart.rst
- docs/source/sensors.rst
Hey all! Cool project and great library! 
I was just going through the documentation and saw two typos which I quickly fixed for you.
Keep up the great work!
> Fixed two typos in the documentation

- powerapi/database/socket_db.py
> Bind socket to 0.0.0.0

- contributing.md
I've completed the contribution guide according to our discussions in the consortium. 
This PR is open for discussions. Don't hesitate to ask for modifications or discuss any aspects. I've tried to keep things simple so maybe some things may not be clear / exhaustive enough
> Complete the contribution guide

- .pylintrc
- src/powerapi/actor/actor.py
- src/powerapi/actor/socket_interface.py
- src/powerapi/cli/config_validator.py
- src/powerapi/cli/parsing_manager.py
- tests/utils/actor/dummy_handlers.py
This PR re-enable pylint `logging-not-lazy` check and fixes all warnings in the codebase.
> refactor: Fix pylint logging-not-lazy warnings

- src/powerapi/processor/pre/k8s/k8s_monitor.py
This PR adds the missing signal (TERM, INT) handler for the `K8sMonitorAgent` process.  
It allows to gracefully stop the monitor process and prevent it to block PowerAPI shutdown.
> fix(processor/k8s): Add missing signal handler to monitor process

- .github/workflows/build.yml
- pyproject.toml
This PR set the minimal Python version to 3.10 for the project.
> build: Bump minimal Python version to 3.10

- src/powerapi/actor/socket_interface.py
This PR fixes a memory usage problem when the actors are slow to process messages.
> fix(actor): Memory usage problem with slow actors

- src/powerapi/dispatcher/route_table.py
- tests/unit/dispatcher/test_dispatcher_actor.py
This PR cleans the code and optimizes the dispatcher's routing table lookup.
> feat(dispatcher): Optimize dispatcher routing table

- src/powerapi/actor/actor.py
- src/powerapi/actor/state.py
- tests/unit/actor/abstract_test_actor.py
This PR cleans the code and optimize the actor's handler lookup.
> feat(actor): Optimize actor handler

- src/powerapi/database/base_db.py
- src/powerapi/database/csvdb.py
- src/powerapi/database/file_db.py
- src/powerapi/database/influxdb2.py
- src/powerapi/database/mongodb.py
- src/powerapi/database/opentsdb.py
- src/powerapi/database/prometheus_db.py
- src/powerapi/database/socket_db.py
- src/powerapi/database/virtiofs_db.py
- src/powerapi/puller/handlers.py
- src/powerapi/puller/puller_actor.py
- tests/utils/db/db.py
This PR adds a `disconnect` method to the databases. (This is preliminary work for the future REST server)
> feat(database): Add `disconnect` method

- src/powerapi/database/prometheus_db.py
- src/powerapi/report/power_report.py
- tests/unit/report/conftest.py
- tests/unit/report/test_power_report.py
Closes: https://github.com/powerapi-ng/powerapi/issues/323
> fix(report): Fix `PowerReport` tags filtering

- src/powerapi/cli/common_cli_parsing_manager.py
- src/powerapi/cli/generator.py
- src/powerapi/database/socket_db.py
- src/powerapi/report/report.py
- tests/utils/cli/several_inputs_outputs_stream_mode_enabled_configuration.json
> feat(database/socket): Allow the socket listen address to be configurable

- CITATION.cff
- README.md
PR overview:
- Adds JOSS paper metadata to `CITATION.cff`
- Adds Zenodo DOI to `CITATION.cff`
- Updates `README.md` to update JOSS badge, add Zenodo DOI badge, and add JOSS publication
Closes: #158
> docs: Update citation metadata
