powerapi-ng/powerapi

- powerapi/database/csvdb.py
When reading several csv files, build one report for each timestamp,
target and do NOT merge different targets in the same report.
> Fix #98 - csv reading : do not merge targets

- powerapi/cli/generator.py
The check on the name was done on model_factory instead of db_factory.
> Fix typo when adding a db factory

- powerapi/actor.py
- powerapi/dispatcher/dispatcher_actor.py
- powerapi/supervisor.py
When extending PowerAPI or developing a formula, it can be necessary to define actors that are not Pullers, Pushers or Dispatcher.
This PR also fixes a few typos in docstrings.
> Feat: allow other actor types

- powerapi/cli/generator.py
- powerapi/report/formula_report.py
- tests/unit/report/test_formula_report.py
This PR rework the Formula report that was not working properly.
This report is needed to debug and compute statistics about a running formula.
> Rework Formula report

- .pylintrc
- src/powerapi/cli/config_parser.py
- src/powerapi/database/csvdb.py
- src/powerapi/database/file_db.py
- src/powerapi/database/virtiofs_db.py
- tests/utils/cli/base_config_parser.py
- tests/utils/report/hwpc.py
This PR re-enable pylint `unspecified-encoding` check and fixes triggered warnings in the codebase.
> refactor: Fix pylint `unspecified-encoding` warnings

- .pylintrc
- src/powerapi/report/power_report.py
- src/powerapi/utils/tree.py
This PR re-enable pylint `protected-access` check and fixes the triggered warnings in the codebase.
> refactor: Fix pylint `protected-access` warnings

- tests/unit/dispatcher/test_dispatcher_actor.py
- tests/utils/db/db.py
- tests/utils/dispatcher/dispatcher.py
This PR fixes some deadlocks happening sometimes when using the `FakeDispatcher` and `FakeDB` in tests.
> test: Fix queue deadlock when terminating actors

- src/powerapi/cli/binding_manager.py
- src/powerapi/dispatcher/dispatcher_actor.py
This PR fixes a pickle error happening when the dispatcher actor is started using multiprocessing `spawn` method.
> fix(dispatcher): Fix pickle error on formula factory when using spawn method

- src/powerapi/database/csvdb.py
This PR fixes the issue #298. When a new target is detected CSV pusher fails because it tries to open a non existent CSV file. Now it creates the file if it doesn't exists.
> fix: create CSV output file when it doesn't exists

- src/powerapi/puller/handlers.py
This PR fixes a bug blocking the puller actor shutdown when its database puller thread is not stopping correctly.
> fix(puller): Set database puller thread as daemon

- src/powerapi/actor/socket_interface.py
- src/powerapi/pusher/handlers.py
This PR fixes the warnings raised by the latest version of pylint about code in the `pusher` and `actor` modules.
> refactor: Fix pylint warnings

- README.md
Adding a badge provided by the [Journal of Open Source Software (JOSS)](https://joss.theoj.org) to report on the status of the paper submission associated to the project.
> Adding JOSS badge

- README.md
Adding a badge and a link to Software Heritage reference to PowerAPI.
> doc: Adding the Software Heritage badge

- Dockerfile
This PR changes how the PowerAPI dependencies are managed inside the container image.
Currently the packages are installed locally for the `powerapi` user, which prevent formula from running under another user, especially when outputs (i.e. `csvdb`) needs to write inside volumes.
After this PR, the packages will be installed inside a global virtualenv, available to every users.
The root user will still be required to install packages, but it is now possible to run a formula with an arbitrary user id.
> build(Dockerfile): Install PowerAPI inside a global Python virtualenv

- .github/workflows/release.yml
PR overview:
- Separate the Python package build and publish steps into two jobs ;
- Build PowerAPI wheel and sdist using [**uv**](https://docs.astral.sh/uv/) ;
- Upload generated wheel and sdist as GitHub Actions artifacts ;
- Add generation of SLSA provenance attestation for the build artifacts ;
- Upload wheel, sdist and SLSA provenance attestation to the GitHub release assets.
> ci(release): Rework python package build/publish steps

- .flake8
- src/powerapi/report/power_report.py
- src/powerapi/report/report.py
- tests/unit/report/conftest.py
- tests/unit/report/test_power_report.py
- tests/unit/report/test_report.py
PR overview:
- Add the `sanitize` and `flattening` methods for the metadata dict of the reports ;
- Update the `PowerReport` to sanitize/flatten its metadata dict for InfluxDB or Prometheus outputs ;
- Rework of the report tags generation method ;
- Improve unit tests for the Prometheus and InfluxDB power report serialization.
Fixes: #408
> feat(report): Allow metadata to be sanitized and flattened

- .github/workflows/build.yml
- pyproject.toml
This PR modifies the way development dependencies are managed in the project:
- Switch to `dependency-groups` [(PEP-735)](https://packaging.python.org/en/latest/specifications/dependency-groups/#dependency-groups) to manage the development dependencies in pyproject.toml ;
- Use `uv` to install the dependencies in the CI build workflow.
> build: Improve development dependencies handling

- .github/workflows/build.yml
- .ruff.toml
- pyproject.toml
This PR adds the [Ruff](https://docs.astral.sh/ruff/) linter configuration file and enable checks in GitHub actions `build` workflow.
> ci: Add `ruff` linter

- .ruff.toml
- src/powerapi/cli/config_validator.py
- src/powerapi/cli/generator.py
- src/powerapi/database/csvdb.py
- src/powerapi/database/file_db.py
- src/powerapi/database/influxdb2.py
- src/powerapi/database/mongodb.py
- src/powerapi/database/opentsdb.py
- src/powerapi/database/prometheus_db.py
- src/powerapi/database/socket_db.py
- src/powerapi/database/virtiofs_db.py
- src/powerapi/dispatch_rule/dispatch_rule.py
- src/powerapi/dispatch_rule/hwpc_dispatch_rule.py
- src/powerapi/dispatch_rule/power_dispatch_rule.py
- src/powerapi/dispatch_rule/procfs_dispatch_rule.py
- src/powerapi/formula/abstract_cpu_dram_formula.py
- src/powerapi/formula/formula_actor.py
- src/powerapi/processor/pre/k8s/metadata_cache_manager.py
- src/powerapi/processor/pre/k8s/monitor_agent.py
- src/powerapi/report/control_report.py
- src/powerapi/report/formula_report.py
- src/powerapi/report/hwpc_report.py
- src/powerapi/report/power_report.py
- src/powerapi/report/procfs_report.py
- src/powerapi/report/report.py
- tests/unit/processor/conftest.py
- tests/unit/processor/pre/k8s/test_monitor_agent.py
- tests/utils/formula/dummy/dummy_formula_actor.py
- tests/utils/report/hwpc.py
[PEP 585 – Type Hinting Generics In Standard Collections](https://peps.python.org/pep-0585/)
> refactor: Use PEP-585 type hints for standard collections

- .ruff.toml
- src/powerapi/dispatch_rule/dispatch_rule.py
- src/powerapi/processor/pre/k8s/metadata_cache_manager.py
- src/powerapi/processor/pre/k8s/monitor_agent.py
[PEP 604 – Allow writing union types as `X | Y`](https://peps.python.org/pep-0604/)
> refactor: Use PEP-604 annotations for union types

- src/powerapi/report/hwpc_report.py
- tests/unit/report/test_hwpc_report.py
Adding verification of rows values when creating HWPC reports in order to raise an exception when CSV files are no complete.
> fix(report/hwpc): Raise `BadInputData` exception when csv line is incomplete

- src/powerapi/database/opentsdb/opentsdb.py
Timestamps from PowerReports are changed when sending data to OpenTSDB, as they are converted to a POSIX time taking into account the local timezone (system timezone). Now timezone info is added to the timestamps before conversion, indicating that they correspond to timezone UTC+00:00.
Fixes #563
> fix(database/opentsdb): Add timezone info to timestamp before sending to OpenTSDB

- .ruff.toml
- src/powerapi/dispatch_rule/hwpc_dispatch_rule.py
[unnecessary-iterable-allocation-for-first-element](https://docs.astral.sh/ruff/rules/unnecessary-iterable-allocation-for-first-element/#unnecessary-iterable-allocation-for-first-element-ruf015)
> refactor: Use iterator to get first element of collections

- .ruff.toml
- tests/unit/actor/abstract_test_actor.py
- tests/unit/actor/test_socket_interface.py
- tests/unit/actor/test_supervisor.py
- tests/unit/cli/conftest.py
- tests/unit/cli/test_binding_manager.py
- tests/unit/processor/pre/k8s/conftest.py
- tests/unit/processor/pre/k8s/test_actor.py
- tests/utils/db/influx2.py
This PR fixes the following pytest related ruff warnings :
- `pytest-raises-too-broad`
- `pytest-assert-always-false`
- `pytest-ueless-yield-fixture`
- `pytest-fixture-incorrect-parentheses-style`
- `pytest-raises-with-multiple-statements`
> refactor: Fix `pytest` related ruff warnings

- .github/dependabot.yml
This PR removes the deprecated `reviewers` field in Dependabot configuration file.
Setting up reviewers for the PR is now managed solely by the `CODEOWNERS` file.
> ci(dependabot): Remove deprecated `reviewers` field

- pyproject.toml
- src/powerapi/cli/common_cli_parsing_manager.py
- src/powerapi/cli/generator.py
- src/powerapi/processor/pre/openstack/__init__.py
- src/powerapi/processor/pre/openstack/_utils.py
- src/powerapi/processor/pre/openstack/actor.py
- src/powerapi/processor/pre/openstack/handlers.py
- src/powerapi/processor/pre/openstack/metadata_cache_manager.py
PR overview:
- Add reports Pre-Processor to add OpenStack server metadata to reports (`HWPCReport`) ;
- Update the configuration parser to handle the OpenStack Pre-Processor parameters ;
- Add the `openstack` platform dependency group in `pyproject.toml` file.
NOTE: The configuration is handled by the OpenStack SDK itself. The documentation about supported parameters is available on the [OpenStack website](https://docs.openstack.org/python-openstackclient/latest/cli/man/openstack.html). Support for openrc files will come in a future PR.
> feat: Add OpenStack platform support
